'use client';
import { LiveDirectoryScreen } from '@/components/screens/LiveDirectoryScreen';
import { MultiActionWorkspace } from '@/components/screens/MultiActionWorkspace';
import { adsService } from '@/services/adsService';
import type { JsonObject } from '@/services/types';
export default function DeliveryMonitorPage() {
  async function update(payload: JsonObject) { const id = String(payload.eventId ?? ''); const isBillable = payload.isBillable === true || payload.isBillable === 'true'; const { eventId: _id, isBillable: _billable, ...body } = payload; return adsService.updateBillableStatus(id, { ...body, isBillable }); }
  return <div className="space-y-6"><LiveDirectoryScreen moduleLabel="Ads" title="Monitor técnico de entrega" description="Ledger técnico de delivery, señales de fraude y elegibilidad de facturación." load={adsService.getDeliveryMonitor} statusOptions={[{ label: 'Facturable', value: 'BILLABLE' }, { label: 'No facturable', value: 'NON_BILLABLE' }, { label: 'Sospechoso', value: 'SUSPICIOUS' }]} columns={[{ key: 'occurredAt', label: 'Fecha/hora', kind: 'date' },{ key: 'eventType', label: 'Evento' },{ key: 'requestId', label: 'Request ID', kind: 'mono' },{ key: 'placementId', label: 'Placement', kind: 'mono' },{ key: 'fraudScore', label: 'Fraude', align: 'right' },{ key: 'billableStatus', label: 'Facturable', kind: 'status' },{ key: 'status', label: 'Estado', kind: 'status' }]} metrics={[{ label: 'Eventos observados', value: (_rows,total) => total, detail: 'Ventana consultada', icon: 'data_usage' },{ label: 'Billables', value: (rows) => rows.filter((row) => String(row.billableStatus).includes('BILLABLE')).length, detail: 'Página actual', icon: 'payments', tone: 'teal' },{ label: 'En revisión', value: (rows) => rows.filter((row) => String(row.status).includes('SUSPICIOUS')).length, detail: 'Validación manual', icon: 'policy', tone: 'amber' },{ label: 'Fraude alto', value: (rows) => rows.filter((row) => Number(row.fraudScore ?? 0) >= .8).length, detail: 'Bloqueo recomendado', icon: 'gpp_bad', tone: 'red' }]} />
    <MultiActionWorkspace moduleLabel="Ads" title="Revisión de facturable" description="Corrija la elegibilidad de facturación con razón obligatoria y trazabilidad." actions={[{ id: 'billable', title: 'Event Billable Status', icon: 'price_check', description: 'Use el UUID exacto del evento seleccionado en el monitor.', submitLabel: 'Guardar decisión', onSubmit: update, fields: [{ name: 'eventId', label: 'UUID evento', required: true, span: 2 }, { name: 'isBillable', label: 'Decisión', type: 'select', valueKind: 'boolean', required: true, options: [{ label: 'Facturable', value: 'true' }, { label: 'No facturable', value: 'false' }] }, { name: 'reason', label: 'Razón', required: true, span: 2, placeholder: 'Mínimo 8 caracteres' }] }]} />
  </div>;
}
