import { Icon } from '@/components/atlas/Icon';
import { InlineNotice } from '@/components/atlas/InlineNotice';
import { MetricCard } from '@/components/atlas/MetricCard';
import { Panel } from '@/components/atlas/Panel';
import { StatusPill } from '@/components/atlas/StatusPill';
import { WorkspaceHeader } from '@/components/atlas/WorkspaceHeader';

export function NotificationsCenterScreen() {
  return <div className="space-y-5"><WorkspaceHeader breadcrumbs={[{ label: 'Administración' }, { label: 'Alertas' }]} title="Centro de notificaciones" description="Centro de monitoreo proactivo y alertas críticas con separación por módulo y severidad." actions={<StatusPill tone="warning">BACKEND PENDIENTE</StatusPill>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Críticas sin leer" value="—" detail="Sin endpoint de bandeja" icon="warning" tone="red" /><MetricCard label="Acciones pendientes" value="—" detail="Sin workflow de alertas" icon="pending_actions" tone="amber" /><MetricCard label="Resueltas hoy" value="—" detail="Sin historial conectado" icon="check_circle" tone="teal" /><MetricCard label="Disponibilidad" value="—" detail="Sin métrica operativa" icon="monitor_heart" /></div>
    <div className="grid gap-4 grid-cols-[minmax(0,1fr)] xl:grid-cols-[minmax(0,1.45fr)_380px]"><Panel title="Alertas críticas" description="La composición respeta la vista original sin mostrar eventos ficticios." icon="notifications_active"><div className="grid min-h-[360px] place-items-center rounded-lg border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><div><Icon name="notifications_off" className="text-[38px] text-slate-400" /><p className="mt-3 text-sm font-bold text-slate-600">No existe una fuente de alertas conectada</p><p className="mt-1 max-w-xl text-xs leading-5 text-slate-500">Se necesita GET /notifications con filtros de severidad, módulo, estado, paginación y permiso de lectura para renderizar esta bandeja.</p></div></div></Panel><div className="space-y-4"><Panel title="Reglas de enrutamiento" icon="alt_route"><Rule label="Seguridad crítica" destination="Security Admin" /><Rule label="Cierre contable" destination="Finance Ops" /><Rule label="Fraude Ads" destination="Ads Compliance" /><Rule label="Mora BNPL" destination="Collections" /></Panel><Panel title="Rastro de auditoría" icon="history"><p className="text-xs leading-5 text-slate-600">Las acciones de reconocer, asignar y resolver deben dejar Business Action Log. Los botones permanecen ausentes hasta existir ese contrato.</p></Panel></div></div><InlineNotice tone="warning">No se han agregado botones decorativos que aparenten resolver alertas. La vista queda preparada para integrarse cuando el backend exponga el módulo.</InlineNotice>
  </div>;
}
function Rule({ label, destination }: { label: string; destination: string }) { return <div className="flex items-center justify-between border-b border-slate-100 py-3 text-xs last:border-0"><div><p className="font-bold">{label}</p><p className="mt-0.5 text-[10px] text-slate-500">{destination}</p></div><Icon name="toggle_off" className="text-[28px] text-slate-400" /></div>; }
