'use client';
import { LiveDirectoryScreen } from '@/components/screens/LiveDirectoryScreen';
import { MultiActionWorkspace } from '@/components/screens/MultiActionWorkspace';
import { adsService } from '@/services/adsService';
import type { JsonObject } from '@/services/types';
export default function CampaignsPage() {
  async function update(payload: JsonObject) { const id = String(payload.campaignId ?? ''); const { campaignId: _id, ...body } = payload; return adsService.updateCampaignStatus(id, body); }
  return <div className="space-y-6"><LiveDirectoryScreen moduleLabel="Ads" title="Campaign Management" description="Seguimiento de campañas, presupuesto, aprobación, entrega y estado operativo." load={adsService.listCampaigns} statusOptions={[{ label: 'Borrador', value: 'DRAFT' }, { label: 'Activa', value: 'ACTIVE' }, { label: 'Pausada', value: 'PAUSED' }, { label: 'Finalizada', value: 'ENDED' }]} columns={[{ key: 'name', label: 'Campaña' },{ key: 'advertiserId', label: 'Anunciante', kind: 'mono' },{ key: 'budgetMicros', label: 'Presupuesto', kind: 'money', align: 'right' },{ key: 'startAt', label: 'Inicio', kind: 'date' },{ key: 'endAt', label: 'Fin', kind: 'date' },{ key: 'approvalStatus', label: 'Aprobación', kind: 'status' },{ key: 'status', label: 'Estado', kind: 'status' }]} metrics={[{ label: 'Campañas', value: (_rows,total) => total, detail: 'Portafolio administrado', icon: 'campaign' },{ label: 'Activas', value: (rows) => rows.filter((row) => row.status === 'ACTIVE').length, detail: 'En delivery', icon: 'play_circle', tone: 'teal' },{ label: 'En aprobación', value: (rows) => rows.filter((row) => String(row.approvalStatus).includes('PENDING')).length, detail: 'Requieren decisión', icon: 'approval', tone: 'amber' },{ label: 'Pausadas', value: (rows) => rows.filter((row) => row.status === 'PAUSED').length, detail: 'Intervención operativa', icon: 'pause_circle', tone: 'red' }]} />
    <MultiActionWorkspace moduleLabel="Ads" title="Campaign Workflow" description="Actualice el estado de una campaña con una razón auditada." actions={[{ id: 'status', title: 'Update Campaign Status', icon: 'published_with_changes', description: 'Aplica una transición permitida por el backend.', submitLabel: 'Actualizar estado', onSubmit: update, fields: [{ name: 'campaignId', label: 'UUID campaña', required: true, span: 2 }, { name: 'status', label: 'Nuevo estado', type: 'select', required: true, options: ['DRAFT','PENDING_REVIEW','APPROVED','ACTIVE','PAUSED','ENDED','REJECTED','ARCHIVED'].map((value) => ({ label: value.replaceAll('_',' '), value })) }, { name: 'reason', label: 'Razón', required: true, placeholder: 'Mínimo 8 caracteres', span: 2 }] }]} />
  </div>;
}
